[build]
  base = "/"
  command = "npm run build && cd examples/nsfw_demo && npm i && npm run build"
  publish = "examples/nsfw_demo/dist"
  edge_functions = "examples/nsfw_demo/netlify/edge-functions"

[build.environment]
NODE_VERSION = "22.13.0"

[[edge_functions]]
  function = "country-block"
  path = "/*"
